apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asya-gateway.fullname" . }}-db
  labels:
    {{- include "asya-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: >-
    postgresql://{{ include "asya-gateway.databaseUsername" . }}:{{ .Values.postgresql.auth.password }}@{{ include "asya-gateway.databaseHost" . }}:{{ include "asya-gateway.databasePort" . }}/{{ include "asya-gateway.databaseName" . }}?sslmode=disable
